# Generated by Django 4.1.3 on 2022-11-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to', '0002_alter_todo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
